apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gsc-be-core
spec:
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 2.5Gi
