-- liquibase formatted sql
-- changeset gcs:202503031700-create-applicant-entities

-- Operator

create table if not exists `operator_applicants` (
    `id` VARCHAR(36) PRIMARY KEY,
    `full_name` VARCHAR(255) NOT NULL,
    `furigana_name` VARCHAR(255),
    `birthday` DATE,
    `gender` VARCHAR(15),
    `project_id` VARCHAR(36),
    `media_applicant_id` VARCHAR(36),
    `email` VARCHAR(255),
    `tel` VARCHAR(15),
    `post_code` VARCHAR(7),
    `prefecture_id` INT,
    `city` VARCHAR(255),
    `home_address` VARCHAR(255),
    `occupation` VARCHAR(36),
    `selection_status_id` bigint,
    `qualification_ids` mediumtext,
    `experience_ids` mediumtext,
    `media_id` VARCHAR(36),
    `manuscript_url` VARCHAR(255),
    `hired_date` DATE,
    `pic_id` VARCHAR(36),
    `memo` TEXT,
    `blacklist1_id` VARCHAR(36),
    `blacklist2_id` VARCHAR(36),
    `is_mail_duplicate` BIT(1) DEFAULT b'0' NOT NULL COMMENT 'メール重複',
    `is_tel_duplicate` BIT(1) DEFAULT b'0' NOT NULL COMMENT '電話重複',
    `is_crawled_data` BIT(1) NOT NULL DEFAULT b'0',
    `lst_status_change_date_time` timestamp DEFAULT NULL COMMENT '24時間以上未対応',
    `lst_contact_date_time` timestamp DEFAULT NULL COMMENT '最新連絡日時',
    `is_unread` BIT(1) DEFAULT b'0' NOT NULL COMMENT '未読',
    `parent_id` VARCHAR(36) NOT NULL,
    `created_at` timestamp NOT NULL DEFAULT current_timestamp,
    `updated_at` timestamp NOT NULL DEFAULT current_timestamp ON update current_timestamp,
    `created_by` VARCHAR(36) NOT NULL,
    `updated_by` VARCHAR(36) NOT NULL,

    FOREIGN KEY (`parent_id`) references `operator_client_accounts` (`id`),
    FOREIGN KEY (`project_id`) references `operator_projects` (`id`),
    FOREIGN KEY (`selection_status_id`) references `selection_statuses` (`id`),
    FOREIGN KEY (`media_id`) references `master_medias` (`id`),
    FOREIGN KEY (`pic_id`) references `operator_client_accounts` (`id`),
    INDEX `applicants_idx_parent_id` (`parent_id`),
    INDEX `applicants_idx_project_id` (`project_id`),
    INDEX `applicants_idx_email` (`email`),
    INDEX `applicants_idx_selection_status_id` (`selection_status_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

create table if not exists `operator_applicant_interviews` (
    `id` VARCHAR(36) PRIMARY KEY,
    `category_id` bigint NOT NULL,
    `interview_start_date` timestamp NOT NULL,
    `interview_end_date` timestamp NOT NULL,
    `pic_id` VARCHAR(36) NOT NULL,
    `memo` TEXT,
    `remind_at` datetime DEFAULT NULL COMMENT 'リマインド日時',
    `applicant_id` VARCHAR(36) NOT NULL,
    `parent_id` VARCHAR(36) NOT NULL,

    FOREIGN KEY (`category_id`) references `interview_categories` (`id`),
    FOREIGN KEY (`pic_id`) references `operator_client_accounts` (`id`),
    FOREIGN KEY (`applicant_id`) references `operator_applicants` (`id`),
    INDEX `idx_parent_id` (`parent_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- OEM

create table if not exists `oem_applicants` (
    `id` VARCHAR(36) PRIMARY KEY,
    `full_name` VARCHAR(255) NOT NULL,
    `furigana_name` VARCHAR(255),
    `birthday` DATE,
    `gender` VARCHAR(15),
    `project_id` VARCHAR(36),
    `media_applicant_id` VARCHAR(36),
    `email` VARCHAR(255),
    `tel` VARCHAR(15),
    `post_code` VARCHAR(7),
    `prefecture_id` INT,
    `city` VARCHAR(255),
    `home_address` VARCHAR(255),
    `occupation` VARCHAR(36),
    `selection_status_id` bigint,
    `qualification_ids` mediumtext,
    `experience_ids` mediumtext,
    `media_id` VARCHAR(36),
    `manuscript_url` VARCHAR(255),
    `hired_date` DATE,
    `pic_id` VARCHAR(36),
    `memo` TEXT,
    `blacklist1_id` VARCHAR(36),
    `blacklist2_id` VARCHAR(36),
    `is_mail_duplicate` BIT(1) DEFAULT b'0' NOT NULL COMMENT 'メール重複',
    `is_tel_duplicate` BIT(1) DEFAULT b'0' NOT NULL COMMENT '電話重複',
    `is_crawled_data` BIT(1) NOT NULL DEFAULT b'0',
    `lst_status_change_date_time` timestamp DEFAULT NULL COMMENT '24時間以上未対応',
    `lst_contact_date_time` timestamp DEFAULT NULL COMMENT '最新連絡日時',
    `is_unread` BIT(1) DEFAULT b'0' NOT NULL COMMENT '未読',
    `parent_id` VARCHAR(36) NOT NULL,
    `oem_group_id` VARCHAR(36) NOT NULL,
    `created_at` timestamp NOT NULL DEFAULT current_timestamp,
    `updated_at` timestamp NOT NULL DEFAULT current_timestamp ON update current_timestamp,
    `created_by` VARCHAR(36) NOT NULL,
    `updated_by` VARCHAR(36) NOT NULL,

    FOREIGN KEY (`parent_id`) references `oem_client_accounts` (`id`),
    FOREIGN KEY (`oem_group_id`) references `oem_groups` (`id`),
    FOREIGN KEY (`project_id`) references `oem_projects` (`id`),
    FOREIGN KEY (`selection_status_id`) references `selection_statuses` (`id`),
    FOREIGN KEY (`media_id`) references `master_medias` (`id`),
    FOREIGN KEY (`pic_id`) references `oem_client_accounts` (`id`),
    INDEX `applicants_idx_parent_id` (`parent_id`),
    INDEX `applicants_idx_oem_group_id` (`oem_group_id`),
    INDEX `applicants_idx_project_id` (`project_id`),
    INDEX `applicants_idx_email` (`email`),
    INDEX `applicants_idx_selection_status_id` (`selection_status_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

create table if not exists `oem_applicant_interviews` (
    `id` VARCHAR(36) PRIMARY KEY,
    `category_id` bigint NOT NULL,
    `interview_start_date` timestamp NOT NULL,
    `interview_end_date` timestamp NOT NULL,
    `pic_id` VARCHAR(36) NOT NULL,
    `memo` TEXT,
    `remind_at` datetime DEFAULT NULL COMMENT 'リマインド日時',
    `applicant_id` VARCHAR(36) NOT NULL,
    `parent_id` VARCHAR(36) NOT NULL,
    `oem_group_id` VARCHAR(36) NOT NULL,

    FOREIGN KEY (`category_id`) references `interview_categories` (`id`),
    FOREIGN KEY (`pic_id`) references `oem_client_accounts` (`id`),
    FOREIGN KEY (`applicant_id`) references `oem_applicants` (`id`),
    INDEX `idx_parent_client_id` (`parent_id`, `oem_group_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
