-- liquibase formatted sql
-- changeset gcs:202502071400-create-project-entities

-- Operator

create table if not exists `operator_projects` (
    `id` VARCHAR(36) PRIMARY KEY,
    `project_number` VARCHAR(255) not null,
    `project_name` VARCHAR(255) not null,
    `status_id` bigint,
    `branch_id` VARCHAR(36),
    `store_id` VARCHAR(36),
    `deadline` DATE,
    `working_hours1` VARCHAR(255),
    `working_hours2` VARCHAR(255),
    `working_hours3` VARCHAR(255),
    `working_days` json,
    `occupation_id` bigint,
    `salary_type` VARCHAR(15),
    `salary_amount` INT,
    `salary_notes` TEXT,
    `employment_type_id` bigint,
    `recruiting_number` INT,
    `gender_restriction` VARCHAR(15),
    `min_age` INT,
    `max_age` INT,
    `not_hiring_condition` TEXT,
    `working_period_id` bigint,
    `desired_start_date` DATE,
    `job_description` TEXT,
    `remarks` TEXT,
    `interview_venue_id` bigint,
    `employment_period_start` DATE,
    `employment_period_end` DATE,
    `is_shift_system` BIT(1),
    `experience_status` VARCHAR(15),
    `portraits` TEXT,
    `qualifications` mediumText,
    `qualification_notes` VARCHAR(400),
    `prefecture_id` INT,
    `city_id` INT,
    `ward` VARCHAR(255),
    `working_hours_notes` TEXT,
    `holidays` VARCHAR(400),
    `benefits` TEXT,
    `ab_adjustment` VARCHAR(15),
    `goal_apply` INT,
    `goal_interview` INT,
    `goal_offer` INT,
    `goal_agreement` INT,
    `memo` TEXT,
    `grouped_by` VARCHAR(15),
    `is_summarized` BIT(1) not null DEFAULT b'0',
    `parent_id` VARCHAR(36) not null,
    `permission` VARCHAR(15),
    `created_at` timestamp NOT NULL DEFAULT current_timestamp,
    `updated_at` timestamp NOT NULL DEFAULT current_timestamp ON update current_timestamp,
    `created_by` VARCHAR(36) NOT NULL,
    `updated_by` VARCHAR(36) NOT NULL,

    FOREIGN KEY (`branch_id`) references `operator_branches` (`id`),
    FOREIGN KEY (`store_id`) references `operator_stores` (`id`),
    FOREIGN KEY (`status_id`) references `master_statuses` (`id`),
    FOREIGN KEY (`occupation_id`) references `master_statuses` (`id`),
    FOREIGN KEY (`employment_type_id`) references `master_statuses` (`id`),
    FOREIGN KEY (`parent_id`) references `operator_client_accounts` (`id`),
    INDEX `projects_idx_occupation_id` (`occupation_id`),
    INDEX `projects_idx_branch_id` (`branch_id`),
    INDEX `projects_idx_parent_id` (`parent_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

create table if not exists `operator_project_linkings` (
    `project1_id` VARCHAR(36) not null,
    `project2_id` VARCHAR(36) not null,

    PRIMARY KEY (project1_id, project2_id),
    FOREIGN KEY (`project1_id`) references `operator_projects` (`id`),
    FOREIGN KEY (`project2_id`) references `operator_projects` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- OEM

create table if not exists `oem_projects` (
    `id` VARCHAR(36) PRIMARY KEY,
    `project_number` VARCHAR(255) not null,
    `project_name` VARCHAR(255) not null,
    `status_id` bigint,
    `branch_id` VARCHAR(36),
    `store_id` VARCHAR(36),
    `deadline` DATE,
    `working_hours1` VARCHAR(255),
    `working_hours2` VARCHAR(255),
    `working_hours3` VARCHAR(255),
    `working_days` json,
    `occupation_id` bigint,
    `salary_type` VARCHAR(15),
    `salary_amount` INT,
    `salary_notes` TEXT,
    `employment_type_id` bigint,
    `recruiting_number` INT,
    `gender_restriction` VARCHAR(15),
    `min_age` INT,
    `max_age` INT,
    `not_hiring_condition` TEXT,
    `working_period_id` bigint,
    `desired_start_date` DATE,
    `job_description` TEXT,
    `remarks` TEXT,
    `interview_venue_id` bigint,
    `employment_period_start` DATE,
    `employment_period_end` DATE,
    `is_shift_system` BIT(1),
    `experience_status` VARCHAR(15),
    `portraits` TEXT,
    `qualifications` mediumText,
    `qualification_notes` VARCHAR(400),
    `prefecture_id` INT,
    `city_id` INT,
    `ward` VARCHAR(255),
    `working_hours_notes` TEXT,
    `holidays` VARCHAR(400),
    `benefits` TEXT,
    `ab_adjustment` VARCHAR(15),
    `goal_apply` INT,
    `goal_interview` INT,
    `goal_offer` INT,
    `goal_agreement` INT,
    `memo` TEXT,
    `grouped_by` VARCHAR(15),
    `is_summarized` BIT(1) not null DEFAULT b'0',
    `parent_id` VARCHAR(36) not null,
    `oem_group_id` VARCHAR(36) not null,
    `permission` VARCHAR(15),
    `created_at` timestamp NOT NULL DEFAULT current_timestamp,
    `updated_at` timestamp NOT NULL DEFAULT current_timestamp ON update current_timestamp,
    `created_by` VARCHAR(36) NOT NULL,
    `updated_by` VARCHAR(36) NOT NULL,

    FOREIGN KEY (`oem_group_id`) references `oem_groups` (`id`),
    FOREIGN KEY (`branch_id`) references `oem_branches` (`id`),
    FOREIGN KEY (`store_id`) references `oem_stores` (`id`),
    FOREIGN KEY (`status_id`) references `master_statuses` (`id`),
    FOREIGN KEY (`occupation_id`) references `master_statuses` (`id`),
    FOREIGN KEY (`employment_type_id`) references `master_statuses` (`id`),
    FOREIGN KEY (`parent_id`) references `oem_client_accounts` (`id`),
    INDEX `projects_idx_occupation_id` (`occupation_id`),
    INDEX `projects_idx_branch_id` (`branch_id`),
    INDEX `projects_idx_parent_id` (`parent_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

create table if not exists `oem_project_linkings` (
    `project1_id` VARCHAR(36) not null,
    `project2_id` VARCHAR(36) not null,

    PRIMARY KEY (project1_id, project2_id),
    FOREIGN KEY (`project1_id`) references `oem_projects` (`id`),
    FOREIGN KEY (`project2_id`) references `oem_projects` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
