apiVersion: v1
kind: Service
metadata:
  name: gsc-be-core
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"gsc-be-core"}}'
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
